endpoint: nodebalancers/%s/configs/%s
url: 'https://developers.linode.com/api/v4#tag/Nodebalancers-Configs'
load-method: get
parameters:
  node_balancer_id:
    type: integer
get:
  get:
    summary: 'View Config'
    description: "Returns configuration information for a single port of this NodeBalancer.\n"
    url: 'https://developers.linode.com/api/v4#operation/getNodeBalancerConfig'
    endpoint: ''
    parameters:
      node_balancer_id:
        description: 'The ID of the NodeBalancer to access.'
        required: true
        type: integer
        self: true
      config_id:
        description: 'The ID of the config to access.'
        required: true
        type: integer
    auto-fill: true
  getNodeBalancerConfigNodes:
    summary: 'List Nodes'
    description: "Returns a paginated list of NodeBalancer nodes associated with this Config. These are the backends that will be sent traffic for this port.\n"
    url: 'https://developers.linode.com/api/v4#operation/getNodeBalancerConfigNodes'
    endpoint: /nodes
    parameters:
      node_balancer_id:
        description: 'The ID of the NodeBalancer to access.'
        required: true
        type: integer
        self: true
      config_id:
        description: 'The ID of the NodeBalancer config to access.'
        required: true
        type: integer
    search: true
    factory:
      class: Node\Balancer\Config\Node
      parameters:
        - id
put:
  update:
    summary: 'Update Config'
    description: "Updates the configuration for a single port on a NodeBalancer.\n"
    url: 'https://developers.linode.com/api/v4#operation/updateNodeBalancerConfig'
    endpoint: ''
    parameters:
      node_balancer_id:
        description: 'The ID of the NodeBalancer to access.'
        required: true
        type: integer
        self: true
      config_id:
        description: 'The ID of the config to access.'
        required: true
        type: integer
    attributes: true
    optional: true
delete:
  delete:
    summary: 'Delete Config'
    description: "Deletes the Config for a port of this NodeBalancer.\n\n**This cannot be undone.**\n\nOnce completed, this NodeBalancer will no longer respond to requests on the given port. This also deletes all associated NodeBalancerNodes, but the Linodes they were routing traffic to will be unchanged and will not be removed.\n"
    url: 'https://developers.linode.com/api/v4#operation/deleteNodeBalancerConfig'
    endpoint: ''
    parameters:
      node_balancer_id:
        description: 'The ID of the NodeBalancer to access.'
        required: true
        type: integer
        self: true
      config_id:
        description: 'The ID of the config to access.'
        required: true
        type: integer
fillable: true
post:
  createNodeBalancerNode:
    summary: 'Create Node'
    description: "Creates a NodeBalancer Node, a backend that can accept traffic for this NodeBalancer Config. Nodes are routed requests on the configured port based on their status.\n"
    url: 'https://developers.linode.com/api/v4#operation/createNodeBalancerNode'
    endpoint: /nodes
    parameters:
      node_balancer_id:
        description: 'The ID of the NodeBalancer to access.'
        required: true
        type: integer
        self: true
      config_id:
        description: "The NodeBalancer Config ID that this Node belongs to.\n"
        type: integer
        required: false
      id:
        description: 'This node''s unique ID.'
        type: integer
        required: false
      address:
        description: "The private IP Address where this backend can be reached. This _must_ be a private IP address.\n"
        type: string
        required: false
      label:
        description: "The label for this node.  This is for display purposes only.\n"
        type: string
        required: false
      status:
        description: "The current status of this node, based on the configured checks of its NodeBalancer Config.\n"
        type: string
        required: false
      weight:
        description: "Used when picking a backend to serve a request and is not pinned to a single backend yet.  Nodes with a higher weight will receive more traffic.\n"
        type: integer
        required: false
      mode:
        description: "The mode this NodeBalancer should use when sending traffic to this backend.\n* If set to `accept` this backend is accepting traffic.\n* If set to `reject` this backend will not receive traffic.\n* If set to `drain` this backend will not receive _new_ traffic, but connections already\n  pinned to it will continue to be routed to it.\n"
        type: string
        required: false
      nodebalancer_id:
        description: "The NodeBalancer ID that this Node belongs to.\n"
        type: integer
        required: false
    attributes: true
    optional: true
